# Numpy - Notes

In [2]:
import numpy as np

## numpy array - Single Dimensional Array

In [12]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [7]:
type(n1)

numpy.ndarray

## numpy array - Multi Dimensional Array

In [13]:
n2 = np.array([[1,2,3,4,5],[6,7,8,9]])
n2

array([list([1, 2, 3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [11]:
type(n2)

numpy.ndarray

## numpy Zeros((a,b)) - creates and initialise zeros with a—>rows & b—>columns

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Numpy full((a,b),n) - initalise with same number with a->rows & b->columns & n->number

In [18]:
np.full((5,5),11)

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

## Numpy arange(a,b,diff) - range of numbers from a to b with difference of diff.

In [23]:
np.arange(10,20,0.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

## Numpy - random.randint(a,b,n) —-> random numbers from a to b with n numbers.

In [27]:
np.random.randint(10,12,5)

array([11, 11, 11, 10, 10])

## Numpy - shape --> number of rows and columns

In [30]:
n2.shape

(2,)

### Numpy - sum([a,b],axis=0) —> add two arrays a and b, optionally add based on horizontal(1) /vertical (0) axis

In [36]:
a = np.array([1,2,3,4,5])
b = np.array([9,8,7,6,5])
np.sum([a,b],axis=1)

array([15, 35])

## Numpy - Vstack (Vertical Stack) - Append arrays row-wise

In [41]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5]])

## Numpy - Hstack (Horizoontal Stack) - Append arrays column-wise

In [43]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 9, 8, 7, 6, 5])

## Numpy - Hstack (Horizontal Stack) - Append arrays in 2-Dimensional Fashion

In [46]:
np.column_stack([a,b])

array([[1, 9],
       [2, 8],
       [3, 7],
       [4, 6],
       [5, 5]])